var esES = {
  "intro": "Bienvenido a Spliced, el juego que te permite dibujar un cadáver exquisito con tus amigos. Examina los puntos a la parte de arriba y la parte de abajo de la pantalla para ver dónde debe empezar y terminar tu sección. Ésto asegurará que todo se mantendrá alineado cuando tu dibujo está combinado con los de tus amigos.",
  "startMessage": "Para empezar, cliquea el botón 'Crear juego'.",
  "createGameButton": "Crear juego",
  "gameCodeMessage": "Si ya tienes un código para el juego, éntralo aquí:",
  "gameCodePrompt": "Tu código",
  "submitButton": "Solicita",
  "galleryMessage": "¡Ve lo que han dibujado otros equipos!",
  "codeIndication" : "Tu código es:",
  "shareLinkMessage": "¡Comparte el enlace con tus amigos!",
  "enterGameButton": "Comenzar juego",
  "drawingFinishMessage": "Gracias por tu dibujo. Favor de esperar hasta que los demás terminen y volver aquí! El imagen aparecerá pocos momentos después de que todos terminen.",
  "fellowArtistsMessage": "Tus compañeros en arte están trabajando en su obra maestra colaborativa. Chequea más tarde, ¡o molesta a tus compañeros para que terminen más de prisa!",
  "upperBodyHead": "Estás dibujando la cabeza.",
  "upperBodyNeck": "Estás dibujando la parte de arriba desde el cuello hasta la cintura.",
  "lowerBodyWaist": "Estás dibujando la parte inferior desde la cintura hasta las rodillas.",
  "lowerBodyKnees": "Estás dibujando la parte inferior desde las rodillas hasta los pies",
  "timeRemainingMessage": "Tiempo que queda:",
  "saveDrawingButton": "Guarda dibujo",
  "undoButton": "Deshaz",
  "startOverButton": "Reinicializa",
  "successMessage": "¡Éxito! Tu dibujo ha sido entregado.",
  "language": "Español",
};