var itIT = {
  "intro": "Benvenuto su Spliced, il gioco che ti permette di disegnare un cadavere squisito con i tuoi amici. Osserva i puntini in cima e in fondo allo schermo per capire dove inizia e finisce la tua sezione. Ciò terrà tutto allineato quando vieni abbinato con gli amici.",
  "startMessage": "Per iniziare, clicca il pulsante Crea Gioco qui sotto!",
  "createGameButton": "Crea Gioco",
  "gameCodeMessage": "Se hai un codice del gioco, inserirlo qui:",
  "gameCodePrompt": "Il tuo codice",
  "submitButton": "Invio",
  "galleryMessage": "Guarda che cosa hanno disegnato le altre squadre!",
  "codeIndication" : "Il tuo codice è:",
  "shareLinkMessage": "Condividi il link con i tuoi amici!",
  "enterGameButton": "Partecipa al gioco",
  "upperBodyHead": "Stai disegnando la parte superiore del corpo: testa",
  "upperBodyNeck": "Stati disegnando la parte superiore del corpo: dal collo alla vita",
  "lowerBodyWaist": "Stati disegnando la parte inferiore del corpo: dalla vita alle ginocchia",
  "lowerBodyKnees": "Stati disegnando la parte inferiore del corpo: dalle ginocchia ai piedi",
  "timeRemainingMessage": "Tempo rimasto: ",
  "saveDrawingButton": "Salva disegno",
  "undoButton": "Annulla",
  "startOverButton": "Ricomincia",
  "successMessage": "Successo! La tua immagine è stata inviata!",
  "drawingFinishMessage": "Ti ringraziamo per il disegno. Aspetta che tutti finiscano e ritorna in un momento successivo! L’immagine apparirà dopo pochi minuti quando tutti hanno finito.",
  "fellowArtistsMessage": "I tuoi colleghi artisti stanno lavorando con impegno al tuo capolavoro collaborativo. Controlla più tardi oppure punzecchiali su questo!",
  "language": "Italiano",
};