var enUS = {
  "intro": "Welcome to Spliced, the game that lets you draw an exquisite corpse with your friends. Look at the dots at the top and bottom of the screen to see where your section should start and stop. This will keep everything lined up when you match up with your friends.",
  "startMessage": "To start, click the Create Game button below!",
  "createGameButton": "Create Game",
  "gameCodeMessage": "If you have a game code, enter it here:",
  "gameCodePrompt": "Your code",
  "submitButton": "Submit",
  "galleryMessage": "See what other teams have drawn!",
  "codeIndication" : "Your Code is:",
  "shareLinkMessage": "Share the link with your friends!",
  "enterGameButton": "Enter Game",
  "upperBodyHead": "You are drawing the upper body: head",
  "upperBodyNeck": "You are drawing the upper body: neck to waist",
  "lowerBodyWaist": "You are drawing the lower body: waist to knees",
  "lowerBodyKnees": "You are drawing the lower body: knees down to feet",
  "timeRemainingMessage": "Time remaining:",
  "saveDrawingButton": "Save Drawing",
  "undoButton": "Undo",
  "startOverButton": "Start Over",
  "successMessage": "Success! Your image has been submitted!",
  "drawingFinishMessage": "Thanks for your drawing. Please wait for everyone to finish and come back later! The image will appear within moments of everyone completing.",
  "fellowArtistsMessage": "Your fellow artists are hard at work on your collaborative masterpiece. Check back later, or bug them about it!",
  "language": "English",
};