angular.module('spliced.home', [])

.controller('HomeController', function ($rootScope, $scope, Draw, Strings, $location) {
  $scope.data = {};

  $rootScope.strings = enUS;

  // Create a game! The callback function has the code that is generated by the server, and updates
  // the user's location to a path with the new game code!
  $scope.createGame = function() {
    Draw.createGame(function(code) {
      console.log(code);
      $location.path('/game/' + code);
    });
  }

  // When a user enters the game code into the form field, they'll get forwarded to the ready screen
  // which allows them to opt in to a drawing.
  $scope.enterCode = function(gameCode) {
    var newUrl = '/game/' + gameCode.toLowerCase();
    $location.path(newUrl);
  }

  $scope.getImages = function () {
    Draw.getImages()
    .then(function (images) {
      console.log("images", images);
      $scope.data.images = images;
    })
    .catch(function (err) {
      console.log(err);
    });
  };

  $scope.chooseEnglish = function() {
    $rootScope.strings = enUS;
  };

  $scope.chooseSpanish = function() {
    $rootScope.strings = esES;
  };

  $scope.chooseFrench = function() {
    $rootScope.strings = frFR;
  };
  
  $scope.chooseItalian = function() {
    $rootScope.strings = itIT;
  };

  $scope.getImages();

});